# Generated by Django 3.2.20 on 2023-07-10 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='price',
            field=models.FloatField(),
        ),
    ]
