# Generated by Django 3.2.20 on 2023-07-10 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_alter_article_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='isOnTrend',
            field=models.BooleanField(default=False),
        ),
    ]
