# Generated by Django 3.2.20 on 2023-07-11 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0008_alter_review_score'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
