# Generated by Django 3.2.20 on 2023-07-11 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0011_article_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
