# Generated by Django 3.2.20 on 2023-07-12 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0013_panier'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Panier',
        ),
    ]
