# Generated by Django 3.2.20 on 2023-07-13 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0014_delete_panier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='dimension',
            field=models.CharField(choices=[('xs', 'Xs'), ('s', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'Xl')], max_length=3),
        ),
    ]
